camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

dfspids: "DFSPID"

zeebe:
  broker:
    contactpoint: "zeebe-zeebe-gateway:26500"

ams:
  local:
    enabled: true
    version: 1.2
    keystore-path: keystore.jks
    keystore-password: openmf
    interop:
      host: https://fynams.sandbox.fynarfin.io
      base-url: /fineract-provider/api/v1
      quotes-path: ${ams.local.interop.base-url}/interoperation/quotes
      parties-path: ${ams.local.interop.base-url}/interoperation/parties/{idType}/{idValue}
      transfers-path: ${ams.local.interop.base-url}/interoperation/transfers
      accounts-path: ${ams.local.interop.base-url}/interoperation/accounts/{externalAccountId}
    customer:
      host: https://fynams.sandbox.fynarfin.io
      base-url: /fineract-provider/api/v1
      path: ${ams.local.customer.base-url}/clients/{clientId}
      image: ${ams.local.customer.base-url}/clients/{clientId}/images
    account:
      host: https://fynams.sandbox.fynarfin.io
      base-url: /fineract-provider/api/v1
      savingsaccounts-path: ${ams.local.account.base-url}/savingsaccounts
    auth:
      host: https://fynams.sandbox.fynarfin.io
    loan:
      host: https://fynams.sandbox.fynarfin.io
      repayment-path: /fineract-provider/api/v1/interoperation/transactions/{accountNumber}/loanrepayment


# Savings : S , Loan : L
accountPrefixes: "S,L"